diff -r Makefile Makefile
4a5
> DOCSHAREDIR = $(SHAREDIR)/doc/$(APPNAME)
115a117
> 	if [ ! -d $(DOCSHAREDIR) ]; then mkdir -p $(DOCSHAREDIR); fi
123,124d124
< 	BUILD/Changelog.txt \
< 	BUILD/License.txt \
126a127,129
> 	
> 	cp BUILD/Changelog.txt $(DOCSHAREDIR)/changelog
> 	gzip $(DOCSHAREDIR)/changelog
