.TH "RealtimeSync" "1" "27 Jul 2012" "" ""
.SH "NAME"
RealtimeSync \(em automated synchronization
.SH "SYNOPSIS"

.PP 
.nf 
RealtimeSync CONFIG_FILE
.fi 
.PP 
.SH "DESCRIPTION"

.PP 
RealtimeSync is a small tool which monitors a directory for changes and
executes a predefined command line on each detected change. Usually the
command line will simply start FreeFileSync to enable real time synchronization.
.PP
.PP 
.SH "AUTHOR"

.PP 
FreeFileSync is written by ZenJu. The Ubuntu release is packaged
by Damien Lecan.
.PP
